services:
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: tienda
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  springboot:
    build: .
    container_name: springboot
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    restart: always

volumes:
  mysql_data:
